### ISSUE TITLE
How to generate a title for a given new text data？

### ISSUE THREAD

**Issue by zhouhao-learning** [hamelsmu/Seq2Seq_Tutorial#10]
After I trained a model, how can I generate a title for the text I entered? Because I saw that the data entered in the prediction in your code is a DF format containing the body and the title, but in practice, I only want to generate a title for the given text, so I don't need the title when predicting, then I What should I do?

Thank You!

**Comment by hamelsmu** [comment]
It’s all there in the code ... please run the code in the tutorial and let me know if you have any questions!
