### ISSUE TITLE
Error in setting encoder_model

### ISSUE THREAD

**Issue by wergeld** [hamelsmu/Seq2Seq_Tutorial#2]
I am following along with this tutorial but am unable to get past this step:
`seq2seq_encoder_out = encoder_model(encoder_inputs)`

This is located at In[20] in the notebook.

This throws the following error:

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-16-8267fe2304ba> in <module>()
> ----> 1 seq2seq_encoder_out = encoder_model(encoder_inputs)
> 
> ~\AppData\Local\Continuum\anaconda3\envs\Seq2Seq\lib\site-packages\keras\engine\topology.py in __call__(self, inputs, **kwargs)
>     615 
>     616             # Actually call the layer, collecting output(s), mask(s), and shape(s).
> --> 617             output = self.call(inputs, **kwargs)
>     618             output_mask = self.compute_mask(inputs, previous_mask)
>     619 
> 
> ~\AppData\Local\Continuum\anaconda3\envs\Seq2Seq\lib\site-packages\keras\engine\topology.py in call(self, inputs, mask)
>    2076             return self._output_tensor_cache[cache_key]
>    2077         else:
> -> 2078             output_tensors, _, _ = self.run_internal_graph(inputs, masks)
>    2079             return output_tensors
>    2080 
> 
> ~\AppData\Local\Continuum\anaconda3\envs\Seq2Seq\lib\site-packages\keras\engine\topology.py in run_internal_graph(self, inputs, masks)
>    2227                                 if 'mask' not in kwargs:
>    2228                                     kwargs['mask'] = computed_mask
> -> 2229                             output_tensors = _to_list(layer.call(computed_tensor, **kwargs))
>    2230                             output_masks = _to_list(layer.compute_mask(computed_tensor,
>    2231                                                                        computed_mask))
> 
> ~\AppData\Local\Continuum\anaconda3\envs\Seq2Seq\lib\site-packages\keras\layers\normalization.py in call(self, inputs, training)
>     183         self.add_update([K.moving_average_update(self.moving_mean,
>     184                                                  mean,
> --> 185                                                  self.momentum),
>     186                          K.moving_average_update(self.moving_variance,
>     187                                                  variance,
> 
> ~\AppData\Local\Continuum\anaconda3\envs\Seq2Seq\lib\site-packages\keras\backend\tensorflow_backend.py in moving_average_update(x, value, momentum)
>     999     """
>    1000     return moving_averages.assign_moving_average(
> -> 1001         x, value, momentum, zero_debias=True)
>    1002 
>    1003 
> 
> ~\AppData\Local\Continuum\anaconda3\envs\Seq2Seq\lib\site-packages\tensorflow\python\training\moving_averages.py in assign_moving_average(variable, value, decay, zero_debias, name)
>      68         decay = math_ops.cast(decay, variable.dtype.base_dtype)
>      69       if zero_debias:
> ---> 70         update_delta = _zero_debias(variable, value, decay)
>      71       else:
>      72         update_delta = (variable - value) * decay
> 
> ~\AppData\Local\Continuum\anaconda3\envs\Seq2Seq\lib\site-packages\tensorflow\python\training\moving_averages.py in _zero_debias(unbiased_var, value, decay)
>     178         local_step_initializer = init_ops.zeros_initializer()
>     179       biased_var = variable_scope.get_variable(
> --> 180           "biased", initializer=biased_initializer, trainable=False)
>     181       local_step = variable_scope.get_variable(
>     182           "local_step",
> 
> ~\AppData\Local\Continuum\anaconda3\envs\Seq2Seq\lib\site-packages\tensorflow\python\ops\variable_scope.py in get_variable(name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter)
>    1063       collections=collections, caching_device=caching_device,
>    1064       partitioner=partitioner, validate_shape=validate_shape,
> -> 1065       use_resource=use_resource, custom_getter=custom_getter)
>    1066 get_variable_or_local_docstring = (
>    1067     """%s
> 
> ~\AppData\Local\Continuum\anaconda3\envs\Seq2Seq\lib\site-packages\tensorflow\python\ops\variable_scope.py in get_variable(self, var_store, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter)
>     960           collections=collections, caching_device=caching_device,
>     961           partitioner=partitioner, validate_shape=validate_shape,
> --> 962           use_resource=use_resource, custom_getter=custom_getter)
>     963 
>     964   def _get_partitioned_variable(self,
> 
> ~\AppData\Local\Continuum\anaconda3\envs\Seq2Seq\lib\site-packages\tensorflow\python\ops\variable_scope.py in get_variable(self, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter)
>     365           reuse=reuse, trainable=trainable, collections=collections,
>     366           caching_device=caching_device, partitioner=partitioner,
> --> 367           validate_shape=validate_shape, use_resource=use_resource)
>     368 
>     369   def _get_partitioned_variable(
> 
> ~\AppData\Local\Continuum\anaconda3\envs\Seq2Seq\lib\site-packages\tensorflow\python\ops\variable_scope.py in _true_getter(name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource)
>     350           trainable=trainable, collections=collections,
>     351           caching_device=caching_device, validate_shape=validate_shape,
> --> 352           use_resource=use_resource)
>     353 
>     354     if custom_getter is not None:
> 
> ~\AppData\Local\Continuum\anaconda3\envs\Seq2Seq\lib\site-packages\tensorflow\python\ops\variable_scope.py in _get_single_variable(self, name, shape, dtype, initializer, regularizer, partition_info, reuse, trainable, collections, caching_device, validate_shape, use_resource)
>     662                          " Did you mean to set reuse=True in VarScope? "
>     663                          "Originally defined at:\n\n%s" % (
> --> 664                              name, "".join(traceback.format_list(tb))))
>     665       found_var = self._vars[name]
>     666       if not shape.is_compatible_with(found_var.get_shape()):
> 
> ValueError: Variable Encoder-Batchnorm-1_1/moving_mean/biased already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:
> 
>   File "C:\Users\lrichards\AppData\Local\Continuum\anaconda3\envs\Seq2Seq\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
>     self._traceback = _extract_stack()
>   File "C:\Users\lrichards\AppData\Local\Continuum\anaconda3\envs\Seq2Seq\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
>     original_op=self._default_original_op, op_def=op_def)
>   File "C:\Users\lrichards\AppData\Local\Continuum\anaconda3\envs\Seq2Seq\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
>     op_def=op_def)

Using Anaconda3 on Windows 7 x64
Tensorflow v1.2.1 (installed via Anaconda)
Keras 2.1.3 (installed via Anaconda)

**Comment by hamelsmu** [comment]
Can you update your version of TensorFlow to the latest and let me know what happens?

**Comment by wergeld** [comment]
Removed tf 1.2.1 and keras 2.1.3.
Used pip to install tf (got 1.5) and keras (same version). Able to proceed through to train the model.
