### ISSUE TITLE
Simplification of requirements.txt

### ISSUE THREAD

**Issue by philgooch** [hamelsmu/Seq2Seq_Tutorial#5]
Happy to make a PR for this if required, but I found that many of the modules in `requirements.txt` are not needed for this tutorial.

If using the AWS Deep Learning Ubuntu AMI, you can simply clone the repo and then just

```
source activate tensorflow_p36
pip install ktext annoy nltk pydot
```

Thanks for this great tutorial, it's one of the few deep learning tutorials that just works out of the box.

**Comment by hamelsmu** [comment]
Glad to hear that!  I don’t want to make this tutorial AWS dependent.  

What do you think  about removing requirements.txt in favor of relying on the Docker container?

**Comment by philgooch** [comment]
> What do you think about removing requirements.txt in favor of relying on the Docker container?

Sounds good to me! Here's what I needed to do to get the Docker container running - might be useful for Docker noobs like me :)  I had no problems running it with the latest Nvidia-Docker. 

```
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey |   sudo apt-key add -
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list |   sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update
sudo apt-get install nvidia-docker

sudo nvidia-docker run hamelsmu/seq2seq_tutorial
```

**Comment by hamelsmu** [comment]
Ok, what about a PR?  It will be good for you to get credit for your idea
